# This file created by conda-build 3.13.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/glib-2.56.2-on-linux_64, last modified Tue Aug 28 16:50:55 2018
# ------------------------------------------------

package:
    name: glib
    version: 2.56.2
source:
    fn: glib-2.56.2.tar.xz
    patches:
        - 0001-F_SETPIPE_SZ-absence-workaround.patch
        - 0001-Revert-Stop-using-ptrctl-for-thread-names.patch
    sha256: d64abd16813501c956c4e123ae79f47f1b58de573df9fdd3b0795f1e2c1aa789
    url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.56/glib-2.56.2.tar.xz
build:
    detect_binary_files_with_prefix: true
    number: '0'
    run_exports:
        - glib >=2.56.2,<2.57.0a0
    string: hd408876_0
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.15.1 pl526h7747ae0_0
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - ca-certificates 2018.03.07 0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gettext 0.19.8.1 hd7bead4_3
        - gettext-cos6-x86_64 0.17 h5b04455_0
        - gettext-devel-cos6-x86_64 0.17 h611b9c9_0
        - gettext-libs-cos6-x86_64 0.17 h1747f9e_0
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libtool 2.4.6 h544aabb_3
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2p h14c3975_0
        - perl 5.26.2 h14c3975_0
        - pkg-config 0.29.2 h1bed415_8
        - python 3.5.5 hc3d631a_4
        - readline 7.0 ha6073c6_4
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    host:
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - pcre 8.42 h439df22_0
        - zlib 1.2.11 ha838bed_2
    run:
        - libffi >=3.2.1,<4.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - pcre >=8.42,<9.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libglib-2.0.so
about:
    description: 'GLib provides the core application building blocks for libraries
        and

        applications written in C. It provides the core object system used in

        GNOME, the main loop implementation, and a large set of utility functions

        functions for strings and common data structures.

        '
    dev_url: https://git.gnome.org/browse/glib/
    doc_source_url: https://git.gnome.org/browse/glib/tree/docs
    doc_url: https://developer.gnome.org/glib/unstable/
    home: https://developer.gnome.org/glib/
    license: LGPL-2.1
    summary: Provides core application building blocks for libraries and applications
        written in C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
        - pkgw
        - scopatz
