# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libpng-1.6.35-on-linux_64, last modified Tue Oct 16 22:00:26 2018
# ------------------------------------------------

package:
    name: libpng
    version: 1.6.35
source:
    fn: libpng-1.6.35.tar.gz
    sha256: 23912ec8c9584917ed9b09c5023465d71709dce089be503c7867fec68a93bcd7
    url: http://download.sourceforge.net/libpng/libpng-1.6.35.tar.xz
build:
    number: '0'
    run_exports:
        - libpng >=1.6.35,<1.7.0a0
    string: hbc83047_0
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.16.1 pl526_0
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libtool 2.4.6 h7b6447c_5
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.2 h14c3975_0
    host:
        - libgcc-ng 8.2.0 hdf63c60_1
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.3.0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libpng.a
        - test -f ${PREFIX}/lib/libpng.so
        - libpng-config --version
        - conda inspect linkages -p $PREFIX libpng
about:
    description: 'libpng is the official PNG reference library. It supports almost
        all PNG

        features, is extensible, and has been extensively tested for over 20 years.

        '
    dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
    doc_url: http://www.libpng.org/pub/png/libpng.html
    home: http://www.libpng.org/pub/png/libpng.html
    license: zlib/libpng
    license_file: LICENSE
    license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
    summary: PNG reference library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
