# This file created by conda-build 3.10.9+36.gd10dbde.dirty
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/mkl_random-feedstock/recipe, last modified Wed Jul  4 06:38:46 2018
# ------------------------------------------------

package:
    name: mkl_random
    version: 1.0.1
source:
    patches:
        - 0001-use-inequality-instead-of-not-identity-for-algo-chec.patch
    sha256: 686b3129f8a5aab079bc03c02a41019994e67d32e6df535bd3b87a186e5f144f
    url: https://github.com/IntelPython/mkl_random/archive/v1.0.1.tar.gz
build:
    number: '1'
    script: python setup.py config build install --old-and-unmanageable
    string: py37h4414c95_1
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - gxx_impl_linux-64 7.2.0 hdf63c60_3
        - gxx_linux-64 7.2.0 h550dcbe_27
        - libstdcxx-ng 7.2.0 hdf63c60_3
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - cython 0.28.3 py37h14c3975_0
        - intel-openmp 2018.0.3 0
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libgfortran-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - mkl 2018.0.3 1
        - mkl-devel 2018.0.3 1
        - mkl-include 2018.0.3 1
        - ncurses 6.1 hf484d3e_0
        - numpy-base 1.11.3 py37hdbf6ddf_8
        - numpy-devel 1.11.3 ha22f7c6_8
        - openssl 1.0.2o h20670df_0
        - python 3.7.0 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - blas 1.0 mkl
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
        - mkl >=2018.0.3
        - numpy >=1.11.3,<2.0a0
        - python >=3.7,<3.8.0a0
test:
    commands:
        - nosetests -v mkl_random
    imports:
        - mkl_random
        - mkl_random.mklrand
    requires:
        - nose
        - numpy >=1.13
about:
    description: NumPy-based implementation of random number generation sampling using
        Intel (R) Math Kernel Library, mirroring numpy.random, but exposing all choices
        of sampling algorithms available in MKL.
    home: http://github.com/IntelPython/mkl_random
    license: BSD 3-Clause
    license_file: LICENSE.txt
    summary: Intel (R) MKL-powered package for sampling from common probability distributions
        into NumPy arrays.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - oleksandr-pavlyk
