# This file created by conda-build 3.8.0
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/pcre-8.42-on-linux_64, last modified Fri Apr 13 13:27:02 2018
# ------------------------------------------------

package:
    name: pcre
    version: '8.42'
source:
    fn: pcre-8.42.tar.gz
    patches:
        - 0001-Define-snprintf-for-old-VS.patch
        - 0002-Workaround-CMake-FIND_PACKAGE-ZLIB-looking-on-PATH-misfeature.patch
    sha256: 69acbc2fbdefb955d42a4c606dfde800c2885711d2979e356c0636efde9ec3b5
    url: ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.42.tar.gz
build:
    number: '0'
    run_exports:
        - pcre >=8.42,<9.0a0
    string: h439df22_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 26
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 26
        - gxx_impl_linux-64 7.2.0 hdf63c60_3
        - gxx_linux-64 7.2.0 26
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libtool 2.4.6 h544aabb_3
        - pkg-config 0.29.2 h1bed415_8
    host:
        - bzip2 1.0.6 h9a117a8_4
        - ca-certificates 2018.03.07 0
        - cmake 3.9.4 h142f0e9_0
        - curl 7.59.0 h84994c4_0
        - expat 2.2.5 he0dffb1_0
        - libcurl 7.59.0 h1ad7b7a_0
        - libgcc-ng 7.2.0 hdf63c60_3
        - libssh2 1.8.0 h9cfc8f7_4
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libuv 1.19.2 h14c3975_0
        - ncurses 6.0 h9df7e31_2
        - openssl 1.0.2o h20670df_0
        - rhash 1.3.5 hbf7ad62_1
        - xz 5.2.3 h55aa19d_2
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
test:
    commands:
        - pcre-config --version
        - pcregrep --help
        - pcretest --help
        - test -f "${PREFIX}/include/pcre.h"
        - test -f "${PREFIX}/include/pcre_scanner.h"
        - test -f "${PREFIX}/include/pcre_stringpiece.h"
        - test -f "${PREFIX}/include/pcrecpp.h"
        - test -f "${PREFIX}/include/pcrecpparg.h"
        - test -f "${PREFIX}/include/pcreposix.h"
        - test -f "${PREFIX}/lib/libpcre.a"
        - test -f "${PREFIX}/lib/libpcre.so"
        - test -f "${PREFIX}/lib/libpcrecpp.a"
        - test -f "${PREFIX}/lib/libpcrecpp.so"
        - test -f "${PREFIX}/lib/libpcreposix.a"
        - test -f "${PREFIX}/lib/libpcreposix.so"
about:
    description: 'PCRE implement regular expression pattern matching using the same
        syntax and

        semantics as Perl 5. PCRE has its own native API, as well as a set of wrapper

        functions that correspond to the POSIX regular expression API.

        '
    dev_url: http://vcs.pcre.org/pcre2/
    doc_source_url: https://vcs.pcre.org/pcre2/code/trunk/doc/?sortdir=down
    doc_url: http://www.pcre.org/original/doc/html/
    home: http://www.pcre.org/
    license: BSD 3-Clause
    license_family: BSD
    summary: Regular expression pattern matching using the same syntax and semantics
        as Perl 5.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - scopatz
        - sebastian-luna-valero
