# This file created by conda-build 3.10.9+36.gd10dbde.dirty
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/sip-feedstock/recipe, last modified Thu Mar 15 13:32:17 2018
# ------------------------------------------------

package:
    name: sip
    version: 4.19.8
source:
    patches:
        - 0001-Do-not-override-CC-CXX-LINK-in-sipgen-Makefile.patch
    sha256: 7eaf7a2ea7d4d38a56dd6d2506574464bddf7cf284c960801679942377c297bc
    url: http://sourceforge.net/projects/pyqt/files/sip/sip-4.19.8/sip-4.19.8.tar.gz
build:
    number: '0'
    string: py37hf484d3e_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - gxx_impl_linux-64 7.2.0 hdf63c60_3
        - gxx_linux-64 7.2.0 h550dcbe_27
        - libstdcxx-ng 7.2.0 hdf63c60_3
    host:
        - ca-certificates 2018.03.07 0
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2o h20670df_0
        - python 3.7.0 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
        - python >=3.7,<3.8.0a0
test:
    files:
        - test
    imports:
        - sip
    requires:
        - gxx_linux-64
about:
    description: 'SIP is a tool that makes it very easy to create Python bindings
        for C and

        C++ libraries. SIP comprises a code generator and a Python module. The

        code generator processes a set of specification files and generates C or

        C++ code which is then compiled to create the bindings extension module.

        The SIP Python module provides support functions to the automatically

        generated code.

        '
    dev_url: https://github.com/ifwe/sip
    doc_url: http://pyqt.sourceforge.net/Docs/sip4/
    home: http://www.riverbankcomputing.com/software/sip/intro
    license: GPL-3.0
    license_file: LICENSE
    summary: Create Python bindings for C and C++ libraries
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
        - msarahan
        - ocefpaf
