# This file created by conda-build 3.16.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/python-3.7.1-on-linux_64, last modified Tue Oct 23 17:34:56 2018
# ------------------------------------------------

package:
    name: python
    version: 3.7.1
source:
    -   md5: 0a57e9022c07fad3dadb2eef58568edb
        patches:
            - 0001-Add-Anaconda-Distribution-version-logic.patch
            - 0002-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
            - 0003-Win32-distutils-Also-look-for-executable.bat.patch
            - 0005-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
            - 0006-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
            - 0007-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
            - 0008-Support-cross-compiling-byte-code.patch
            - 0009-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
            - 0010-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
            - 0011-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
            - 0012-Win32-Do-not-download-externals.patch
            - 0013-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
            - 0014-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
            - 0015-Disable-new-dtags-in-unixccompiler.py.patch
            - 0016-Switch-from-WinSDK-10.0.17134.0-to-10.0.16299.0.patch
            - 0017-Fix-cross-compilation-on-Debian-based-distros.patch
        url: https://www.python.org/ftp/python/3.7.1/Python-3.7.1.tar.xz
build:
    ignore_run_exports:
        - bzip2
    number: '3'
    string: h0371630_3
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - make 4.2.1 h1bed415_1
        - pkg-config 0.29.2 h1bed415_8
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    host:
        - bzip2 1.0.6 h14c3975_5
        - ca-certificates 2018.03.07 0
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.1.1 h7b6447c_0
        - readline 7.0 h7b6447c_5
        - sqlite 3.25.2 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - libffi >=3.2.1,<4.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - ncurses >=6.1,<7.0a0
        - openssl >=1.1.1,<1.1.2.0a0
        - readline >=7.0,<8.0a0
        - sqlite >=3.25.2,<4.0a0
        - tk >=8.6.8,<8.7.0a0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - python -V
        - python3 -V
        - 2to3 -h
        - pydoc -h
        - python3-config --help
        - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
        - _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
            python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
about:
    description: 'Python is a widely used high-level, general-purpose, interpreted,
        dynamic

        programming language. Its design philosophy emphasizes code

        readability, and its syntax allows programmers to express concepts in

        fewer lines of code than would be possible in languages such as C++ or

        Java. The language provides constructs intended to enable clear programs

        on both a small and large scale.

        '
    dev_url: https://docs.python.org/devguide/
    doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
    doc_url: https://www.python.org/doc/versions/
    home: http://www.python.org/
    license: PSF
    license_file: LICENSE
    summary: General purpose programming language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
