# This file created by conda-build 3.10.9+36.gd10dbde.dirty
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/kiwisolver-feedstock/recipe, last modified Mon Dec  4 23:17:47 2017
# ------------------------------------------------

package:
    name: kiwisolver
    version: 1.0.1
source:
    fn: kiwisolver-1.0.1.tar.gz
    sha256: 8e7fc64fea6d3af96aed63391d35bbbd292a429c8e463277dac839b735503a28
    url: https://github.com/nucleic/kiwi/archive/1.0.1.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37hf484d3e_0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - gxx_impl_linux-64 7.2.0 hdf63c60_3
        - gxx_linux-64 7.2.0 h550dcbe_27
        - libstdcxx-ng 7.2.0 hdf63c60_3
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2o h20670df_0
        - python 3.7.0 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - libgcc-ng >=7.2.0
        - libstdcxx-ng >=7.2.0
        - python >=3.7,<3.8.0a0
test:
    imports:
        - kiwisolver
about:
    description: 'Kiwi is an implementation of the algorithm based on the seminal

        Cassowary paper.It is not a refactoring of the original C++ solver.

        Kiwi has been designed from the ground up to be lightweight and fast.

        '
    dev_url: https://github.com/nucleic/kiwi
    doc_source_url: https://github.com/nucleic/kiwi/blob/master/README.rst
    doc_url: https://pypi.python.org/pypi/kiwisolver
    home: https://github.com/nucleic/kiwi
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING.txt
    summary: A fast implementation of the Cassowary constraint solver
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MatthieuDartiailh
        - blink1073
        - ericdill
        - licode
        - sccolbert
        - tacaswell
