# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/wheel-0.32.2-python_3.7-on-linux_64, last modified Mon Oct 22 17:04:49 2018
# ------------------------------------------------

package:
    name: wheel
    version: 0.32.2
source:
    sha256: 196c9842d79262bb66fcf59faa4bd0deb27da911dbc7c6cdca931080eb1f0783
    url: https://pypi.io/packages/source/w/wheel/wheel-0.32.2.tar.gz
build:
    entry_points:
        - wheel = wheel.cli:main
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2p h14c3975_0
        - python 3.7.0 h6e4f718_3
        - readline 7.0 h7b6447c_5
        - setuptools 40.4.3 py37_0
        - sqlite 3.25.2 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    commands:
        - wheel --help
    imports:
        - wheel
about:
    home: https://github.com/pypa/wheel
    license: MIT
    license_file: LICENSE.txt
    summary: A built-package format for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
