# This file created by conda-build 3.16.1
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/matplotlib-3.0.1-python_3.7-on-linux_64, last modified Thu Oct 25 16:38:05 2018
# ------------------------------------------------

package:
    name: matplotlib
    version: 3.0.1
source:
    patches:
        - cfg_qt5agg.patch
    sha256: 147306a20b2ec29ba5dcc8a8fdada57d5d7eb0aa7e42af984e762d956c97b0d5
    url: https://github.com/matplotlib/matplotlib/archive/v3.0.1.tar.gz
build:
    ignore_run_exports:
        - pyqt
    number: '0'
    string: py37h5429711_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - blas 1.0 mkl
        - ca-certificates 2018.03.07 0
        - certifi 2018.10.15 py37_0
        - cycler 0.10.0 py37_0
        - dbus 1.13.2 h714fa37_1
        - expat 2.2.6 he6710b0_0
        - fontconfig 2.13.0 h9420a91_0
        - freetype 2.9.1 h8a8886c_1
        - glib 2.56.2 hd408876_0
        - gst-plugins-base 1.14.0 hbbd80ab_1
        - gstreamer 1.14.0 hb453b48_1
        - icu 58.2 h9c2bf20_1
        - intel-openmp 2019.0 118
        - jpeg 9b h024ee3a_2
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 8.2.0 hdf63c60_1
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libpng 1.6.35 hbc83047_0
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - libuuid 1.0.3 h1bed415_2
        - libxcb 1.13 h1bed415_1
        - libxml2 2.9.8 h26e45fe_1
        - mkl 2019.0 118
        - ncurses 6.1 hf484d3e_0
        - nose 1.3.7 py37_2
        - numpy 1.11.3 py37h1d66e8a_10
        - numpy-base 1.11.3 py37h81de0dd_10
        - openssl 1.0.2p h14c3975_0
        - pcre 8.42 h439df22_0
        - pkg-config 0.29.2 h1bed415_8
        - pyparsing 2.2.2 py37_0
        - pyqt 5.9.2 py37h05f1152_2
        - python 3.7.0 h6e4f718_3
        - python-dateutil 2.7.3 py37_0
        - pytz 2018.5 py37_0
        - qt 5.9.6 h8703b6f_2
        - readline 7.0 h7b6447c_5
        - setuptools 40.4.3 py37_0
        - sip 4.19.8 py37hf484d3e_0
        - six 1.11.0 py37_1
        - sqlite 3.25.2 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - cycler >=0.10
        - freetype >=2.9.1,<3.0a0
        - icu >=58.2,<59.0a0
        - kiwisolver
        - libgcc-ng >=7.3.0
        - libpng >=1.6.35,<1.7.0a0
        - libstdcxx-ng >=7.3.0
        - numpy
        - pyparsing
        - pyqt 5.9.*
        - python >=3.7,<3.8.0a0
        - python-dateutil
        - pytz
        - setuptools
        - tk 8.6.*
        - tk >=8.6.8,<8.7.0a0
        - tornado
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
    imports:
        - matplotlib
        - matplotlib._image
        - matplotlib._path
        - matplotlib._png
        - matplotlib._tri
        - matplotlib.backends._backend_agg
        - matplotlib.backends._tkagg
        - matplotlib.ft2font
        - matplotlib.pyplot
        - matplotlib.ttconv
        - mpl_toolkits
        - pylab
about:
    description: 'matplotlib is a python 2D plotting library which produces publication

        quality figures in a variety of hardcopy formats and interactive

        environments across platforms. matplotlib can be used in Python scripts,

        the Python and IPython shell (ala MATLAB or Mathematica), web

        application servers, and six graphical user interface toolkits.

        '
    dev_url: https://github.com/matplotlib/matplotlib/
    doc_url: http://matplotlib.org/contents.html
    home: http://matplotlib.org/
    license: PSF-based
    license_family: PSF
    license_file: LICENSE/LICENSE
    license_url: http://matplotlib.sourceforge.net/users/license.html
    summary: Publication quality figures in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - mdboom
        - ocefpaf
        - pelson
        - tacaswell
