# This file created by conda-build 3.10.3
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/libxml2-2.9.8-on-linux_64, last modified Wed May 23 02:47:15 2018
# ------------------------------------------------

package:
    name: libxml2
    version: 2.9.8
source:
    patches:
        - 0001-C89-for-VS2008.patch
        - 0004-CVE-2017-8872.patch
    sha256: 0b74e51595654f958148759cfef0993114ddccccbb6f31aee018f3558e8e2732
    url: ftp://xmlsoft.org/libxml2/libxml2-2.9.8.tar.gz
build:
    number: '1'
    run_exports:
        - libxml2 >=2.9.8,<2.10.0a0
    string: h26e45fe_1
requirements:
    build:
        - autoconf 2.69 pl526hebd4dad_5
        - automake 1.15.1 pl526h7747ae0_0
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - binutils_linux-64 7.2.0 had2808c_27
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 h550dcbe_27
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - libtool 2.4.6 h544aabb_3
        - m4 1.4.18 h4e445db_0
        - make 4.2.1 h1bed415_1
        - perl 5.26.0 hae598fd_0
        - pkg-config 0.29.2 h1bed415_8
    host:
        - icu 58.2 h9c2bf20_1
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - icu >=58.2,<59.0a0
        - libgcc-ng >=7.2.0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - xmllint test.xml
        - conda inspect linkages -p $PREFIX libxml2
    files:
        - test.xml
about:
    description: 'Though libxml2 is written in C a variety of language

        bindings make it available in other environments.

        '
    dev_url: https://git.gnome.org/browse/libxml2/
    doc_source_url: https://github.com/GNOME/libxml2/blob/master/doc/index.html
    doc_url: http://xmlsoft.org/html/index.html
    home: http://xmlsoft.org/
    license: MIT
    license_family: MIT
    license_file: Copyright
    summary: The XML C parser and toolkit of Gnome
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - jakirkham
        - jschueller
        - mingwandroid
        - msarahan
        - ocefpaf
