# This file created by conda-build 3.10.9+36.gd10dbde.dirty
# meta.yaml template originally from:
# /home/rdonnelly/conda/aggregate/cssselect-feedstock/recipe, last modified Mon Jan 29 12:00:21 2018
# ------------------------------------------------

package:
    name: cssselect
    version: 1.0.3
source:
    fn: cssselect-1.0.3.tar.gz
    sha256: 203d9691c42c13cffe26a2f8fc714977882fcf54a6df82c8eda3371f6beaecdb
    url: https://github.com/scrapy/cssselect/archive/v1.0.3.tar.gz
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py37_0
requirements:
    host:
        - ca-certificates 2018.03.07 0
        - certifi 2018.4.16 py37_0
        - libedit 3.1.20170329 h6b74fdf_2
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hf484d3e_0
        - openssl 1.0.2o h20670df_0
        - python 3.7.0 hc3d631a_0
        - readline 7.0 ha6073c6_4
        - setuptools 39.2.0 py37_0
        - sqlite 3.24.0 h84994c4_0
        - tk 8.6.7 hc745277_3
        - xz 5.2.4 h14c3975_4
        - zlib 1.2.11 ha838bed_2
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - cssselect
about:
    description: 'Cssselect parses CSS3 Selectors and translate them to XPath 1.0

        expressions. Such expressions can be used in lxml or another XPath engine

        to find the matching elements in an XML or HTML document.

        '
    dev_url: https://github.com/SimonSapin/cssselect
    doc_source_url: https://github.com/scrapy/cssselect/blob/master/README.rst
    doc_url: https://cssselect.readthedocs.io/en/latest/
    home: https://pythonhosted.org/cssselect/
    license: BSD 3-Clause
    license_file: LICENSE
    summary: CSS Selectors for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - vamega
